/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UUID = IDL.Nat;
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MainTopic = IDL.Record({
  'id' : UUID,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'creationDate' : Time,
});
export const RevisionSchedule = IDL.Record({
  'owner' : IDL.Principal,
  'isReviewed' : IDL.Bool,
  'subTopicId' : UUID,
  'intervalDays' : IDL.Nat,
  'studyDate' : Time,
  'nextReview' : Time,
  'reviewCount' : IDL.Nat,
});
export const SubTopic = IDL.Record({
  'id' : UUID,
  'title' : IDL.Text,
  'lastReviewed' : IDL.Opt(Time),
  'currentIntervalIndex' : IDL.Nat,
  'owner' : IDL.Principal,
  'difficulty' : Difficulty,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'creationDate' : Time,
  'studyDate' : Time,
  'mainTopicTitle' : IDL.Text,
  'mainTopicId' : UUID,
});
export const RevisionResult = IDL.Record({
  'message' : IDL.Text,
  'updatedSchedule' : IDL.Opt(RevisionSchedule),
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMainTopic' : IDL.Func([IDL.Text, IDL.Text], [UUID], []),
  'createSubTopic' : IDL.Func(
      [UUID, IDL.Text, IDL.Text, Difficulty, Time],
      [UUID],
      [],
    ),
  'deleteMainTopic' : IDL.Func([UUID], [], []),
  'deleteSubTopic' : IDL.Func([UUID], [], []),
  'getAllPlannedRevisionDates' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'plannedDates' : IDL.Vec(Time),
            'owner' : IDL.Principal,
            'difficulty' : Difficulty,
            'subTopicId' : UUID,
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDefaultIntervalDays' : IDL.Func(
      [],
      [
        IDL.Record({
          'easy' : IDL.Vec(IDL.Nat),
          'hard' : IDL.Vec(IDL.Nat),
          'medium' : IDL.Vec(IDL.Nat),
        }),
      ],
      ['query'],
    ),
  'getIntervalForDifficulty' : IDL.Func(
      [Difficulty],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getMainTopics' : IDL.Func([], [IDL.Vec(MainTopic)], ['query']),
  'getPlannedRevisionDates' : IDL.Func(
      [UUID],
      [IDL.Opt(IDL.Vec(Time))],
      ['query'],
    ),
  'getRevisionSchedule' : IDL.Func([], [IDL.Vec(RevisionSchedule)], ['query']),
  'getSubTopics' : IDL.Func([], [IDL.Vec(SubTopic)], ['query']),
  'getSubTopicsByMainTopic' : IDL.Func([UUID], [IDL.Vec(SubTopic)], ['query']),
  'getSubTopicsForDate' : IDL.Func([Time], [IDL.Vec(SubTopic)], ['query']),
  'getSubTopicsWithStudyDates' : IDL.Func([], [IDL.Vec(SubTopic)], ['query']),
  'getTodaySubTopics' : IDL.Func([], [IDL.Vec(SubTopic)], ['query']),
  'getTopicsWithHierarchy' : IDL.Func(
      [],
      [
        IDL.Record({
          'subTopics' : IDL.Vec(SubTopic),
          'mainTopics' : IDL.Vec(MainTopic),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'easyIntervals' : IDL.Vec(IDL.Nat),
            'mediumIntervals' : IDL.Vec(IDL.Nat),
            'preferredReviewDays' : IDL.Vec(IDL.Nat),
            'hardIntervals' : IDL.Vec(IDL.Nat),
          })
        ),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markRevisionAsReviewed' : IDL.Func([UUID], [], []),
  'markSubTopicCompleted' : IDL.Func([UUID], [], []),
  'markSubTopicPending' : IDL.Func([UUID], [], []),
  'rescheduleRevisionToNextDay' : IDL.Func([UUID], [RevisionResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleNextReview' : IDL.Func([UUID, IDL.Nat], [], []),
  'setUserSettings' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
  'updateIntervalIndex' : IDL.Func([UUID, IDL.Nat], [], []),
  'updateMainTopic' : IDL.Func([UUID, IDL.Text, IDL.Text], [], []),
  'updateRevisionSchedule' : IDL.Func([UUID], [RevisionSchedule], []),
  'updateSubTopic' : IDL.Func(
      [UUID, IDL.Text, IDL.Text, Difficulty, Time],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UUID = IDL.Nat;
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MainTopic = IDL.Record({
    'id' : UUID,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'creationDate' : Time,
  });
  const RevisionSchedule = IDL.Record({
    'owner' : IDL.Principal,
    'isReviewed' : IDL.Bool,
    'subTopicId' : UUID,
    'intervalDays' : IDL.Nat,
    'studyDate' : Time,
    'nextReview' : Time,
    'reviewCount' : IDL.Nat,
  });
  const SubTopic = IDL.Record({
    'id' : UUID,
    'title' : IDL.Text,
    'lastReviewed' : IDL.Opt(Time),
    'currentIntervalIndex' : IDL.Nat,
    'owner' : IDL.Principal,
    'difficulty' : Difficulty,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'creationDate' : Time,
    'studyDate' : Time,
    'mainTopicTitle' : IDL.Text,
    'mainTopicId' : UUID,
  });
  const RevisionResult = IDL.Record({
    'message' : IDL.Text,
    'updatedSchedule' : IDL.Opt(RevisionSchedule),
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMainTopic' : IDL.Func([IDL.Text, IDL.Text], [UUID], []),
    'createSubTopic' : IDL.Func(
        [UUID, IDL.Text, IDL.Text, Difficulty, Time],
        [UUID],
        [],
      ),
    'deleteMainTopic' : IDL.Func([UUID], [], []),
    'deleteSubTopic' : IDL.Func([UUID], [], []),
    'getAllPlannedRevisionDates' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'plannedDates' : IDL.Vec(Time),
              'owner' : IDL.Principal,
              'difficulty' : Difficulty,
              'subTopicId' : UUID,
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDefaultIntervalDays' : IDL.Func(
        [],
        [
          IDL.Record({
            'easy' : IDL.Vec(IDL.Nat),
            'hard' : IDL.Vec(IDL.Nat),
            'medium' : IDL.Vec(IDL.Nat),
          }),
        ],
        ['query'],
      ),
    'getIntervalForDifficulty' : IDL.Func(
        [Difficulty],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getMainTopics' : IDL.Func([], [IDL.Vec(MainTopic)], ['query']),
    'getPlannedRevisionDates' : IDL.Func(
        [UUID],
        [IDL.Opt(IDL.Vec(Time))],
        ['query'],
      ),
    'getRevisionSchedule' : IDL.Func(
        [],
        [IDL.Vec(RevisionSchedule)],
        ['query'],
      ),
    'getSubTopics' : IDL.Func([], [IDL.Vec(SubTopic)], ['query']),
    'getSubTopicsByMainTopic' : IDL.Func(
        [UUID],
        [IDL.Vec(SubTopic)],
        ['query'],
      ),
    'getSubTopicsForDate' : IDL.Func([Time], [IDL.Vec(SubTopic)], ['query']),
    'getSubTopicsWithStudyDates' : IDL.Func([], [IDL.Vec(SubTopic)], ['query']),
    'getTodaySubTopics' : IDL.Func([], [IDL.Vec(SubTopic)], ['query']),
    'getTopicsWithHierarchy' : IDL.Func(
        [],
        [
          IDL.Record({
            'subTopics' : IDL.Vec(SubTopic),
            'mainTopics' : IDL.Vec(MainTopic),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'easyIntervals' : IDL.Vec(IDL.Nat),
              'mediumIntervals' : IDL.Vec(IDL.Nat),
              'preferredReviewDays' : IDL.Vec(IDL.Nat),
              'hardIntervals' : IDL.Vec(IDL.Nat),
            })
          ),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markRevisionAsReviewed' : IDL.Func([UUID], [], []),
    'markSubTopicCompleted' : IDL.Func([UUID], [], []),
    'markSubTopicPending' : IDL.Func([UUID], [], []),
    'rescheduleRevisionToNextDay' : IDL.Func([UUID], [RevisionResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleNextReview' : IDL.Func([UUID, IDL.Nat], [], []),
    'setUserSettings' : IDL.Func(
        [
          IDL.Vec(IDL.Nat),
          IDL.Vec(IDL.Nat),
          IDL.Vec(IDL.Nat),
          IDL.Vec(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateIntervalIndex' : IDL.Func([UUID, IDL.Nat], [], []),
    'updateMainTopic' : IDL.Func([UUID, IDL.Text, IDL.Text], [], []),
    'updateRevisionSchedule' : IDL.Func([UUID], [RevisionSchedule], []),
    'updateSubTopic' : IDL.Func(
        [UUID, IDL.Text, IDL.Text, Difficulty, Time],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };