/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface MainTopic {
  'id' : UUID,
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'creationDate' : Time,
}
export interface RevisionSchedule {
  'owner' : Principal,
  'subTopicId' : UUID,
  'intervalDays' : bigint,
  'studyDate' : Time,
  'nextReview' : Time,
}
export interface SubTopic {
  'id' : UUID,
  'title' : string,
  'lastReviewed' : [] | [Time],
  'currentIntervalIndex' : bigint,
  'owner' : Principal,
  'difficulty' : Difficulty,
  'completed' : boolean,
  'description' : string,
  'creationDate' : Time,
  'studyDate' : Time,
  'mainTopicTitle' : string,
  'mainTopicId' : UUID,
}
export type Time = bigint;
export type UUID = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMainTopic' : ActorMethod<[string, string], UUID>,
  'createSubTopic' : ActorMethod<
    [UUID, string, string, Difficulty, Time],
    UUID
  >,
  'deleteMainTopic' : ActorMethod<[UUID], undefined>,
  'deleteSubTopic' : ActorMethod<[UUID], undefined>,
  'getAllPlannedRevisionDates' : ActorMethod<
    [],
    Array<
      {
        'plannedDates' : Array<Time>,
        'owner' : Principal,
        'difficulty' : Difficulty,
        'subTopicId' : UUID,
      }
    >
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDefaultIntervalDays' : ActorMethod<
    [],
    { 'easy' : Array<bigint>, 'hard' : Array<bigint>, 'medium' : Array<bigint> }
  >,
  'getIntervalForDifficulty' : ActorMethod<[Difficulty], Array<bigint>>,
  'getMainTopics' : ActorMethod<[], Array<MainTopic>>,
  'getPlannedRevisionDates' : ActorMethod<[UUID], [] | [Array<Time>]>,
  'getRevisionSchedule' : ActorMethod<[], Array<RevisionSchedule>>,
  'getSubTopics' : ActorMethod<[], Array<SubTopic>>,
  'getSubTopicsByMainTopic' : ActorMethod<[UUID], Array<SubTopic>>,
  'getSubTopicsForDate' : ActorMethod<[Time], Array<SubTopic>>,
  'getSubTopicsWithStudyDates' : ActorMethod<[], Array<SubTopic>>,
  'getTodaySubTopics' : ActorMethod<[], Array<SubTopic>>,
  'getTopicsWithHierarchy' : ActorMethod<
    [],
    { 'subTopics' : Array<SubTopic>, 'mainTopics' : Array<MainTopic> }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSettings' : ActorMethod<
    [],
    [] | [
      {
        'easyIntervals' : Array<bigint>,
        'mediumIntervals' : Array<bigint>,
        'preferredReviewDays' : Array<bigint>,
        'hardIntervals' : Array<bigint>,
      }
    ]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markSubTopicCompleted' : ActorMethod<[UUID], undefined>,
  'markSubTopicPending' : ActorMethod<[UUID], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleNextReview' : ActorMethod<[UUID, bigint], undefined>,
  'setUserSettings' : ActorMethod<
    [Array<bigint>, Array<bigint>, Array<bigint>, Array<bigint>],
    undefined
  >,
  'updateIntervalIndex' : ActorMethod<[UUID, bigint], undefined>,
  'updateMainTopic' : ActorMethod<[UUID, string, string], undefined>,
  'updateRevisionSchedule' : ActorMethod<[UUID], RevisionSchedule>,
  'updateSubTopic' : ActorMethod<
    [UUID, string, string, Difficulty, Time],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];