/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MainTopic {
    id: UUID;
    title: string;
    owner: Principal;
    description: string;
    creationDate: Time;
}
export type Time = bigint;
export type UUID = bigint;
export interface SubTopic {
    id: UUID;
    title: string;
    lastReviewed?: Time;
    currentIntervalIndex: bigint;
    owner: Principal;
    difficulty: Difficulty;
    completed: boolean;
    description: string;
    creationDate: Time;
    studyDate: Time;
    mainTopicTitle: string;
    mainTopicId: UUID;
}
export interface RevisionSchedule {
    owner: Principal;
    isReviewed: boolean;
    subTopicId: UUID;
    intervalDays: bigint;
    studyDate: Time;
    nextReview: Time;
    reviewCount: bigint;
}
export interface RevisionResult {
    message: string;
    updatedSchedule?: RevisionSchedule;
    success: boolean;
}
export interface UserProfile {
    name: string;
}
export enum Difficulty {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createMainTopic(title: string, description: string): Promise<UUID>;
    createSubTopic(mainTopicId: UUID, title: string, description: string, difficulty: Difficulty, studyDate: Time): Promise<UUID>;
    deleteMainTopic(id: UUID): Promise<void>;
    deleteSubTopic(id: UUID): Promise<void>;
    getAllPlannedRevisionDates(): Promise<Array<{
        plannedDates: Array<Time>;
        owner: Principal;
        difficulty: Difficulty;
        subTopicId: UUID;
    }>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDefaultIntervalDays(): Promise<{
        easy: Array<bigint>;
        hard: Array<bigint>;
        medium: Array<bigint>;
    }>;
    getIntervalForDifficulty(difficulty: Difficulty): Promise<Array<bigint>>;
    getMainTopics(): Promise<Array<MainTopic>>;
    getPlannedRevisionDates(subTopicId: UUID): Promise<Array<Time> | null>;
    getRevisionSchedule(): Promise<Array<RevisionSchedule>>;
    getSubTopics(): Promise<Array<SubTopic>>;
    getSubTopicsByMainTopic(mainTopicId: UUID): Promise<Array<SubTopic>>;
    getSubTopicsForDate(targetDate: Time): Promise<Array<SubTopic>>;
    getSubTopicsWithStudyDates(): Promise<Array<SubTopic>>;
    getTodaySubTopics(): Promise<Array<SubTopic>>;
    getTopicsWithHierarchy(): Promise<{
        subTopics: Array<SubTopic>;
        mainTopics: Array<MainTopic>;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSettings(): Promise<{
        easyIntervals: Array<bigint>;
        mediumIntervals: Array<bigint>;
        preferredReviewDays: Array<bigint>;
        hardIntervals: Array<bigint>;
    } | null>;
    isCallerAdmin(): Promise<boolean>;
    markRevisionAsReviewed(subTopicId: UUID): Promise<void>;
    markSubTopicCompleted(id: UUID): Promise<void>;
    markSubTopicPending(id: UUID): Promise<void>;
    rescheduleRevisionToNextDay(subTopicId: UUID): Promise<RevisionResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    scheduleNextReview(subTopicId: UUID, days: bigint): Promise<void>;
    setUserSettings(easyIntervals: Array<bigint>, mediumIntervals: Array<bigint>, hardIntervals: Array<bigint>, preferredDays: Array<bigint>): Promise<void>;
    updateIntervalIndex(subTopicId: UUID, newIndex: bigint): Promise<void>;
    updateMainTopic(id: UUID, title: string, description: string): Promise<void>;
    updateRevisionSchedule(subTopicId: UUID): Promise<RevisionSchedule>;
    updateSubTopic(id: UUID, title: string, description: string, difficulty: Difficulty, studyDate: Time): Promise<void>;
}
import type { Difficulty as _Difficulty, MainTopic as _MainTopic, RevisionResult as _RevisionResult, RevisionSchedule as _RevisionSchedule, SubTopic as _SubTopic, Time as _Time, UUID as _UUID, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMainTopic(arg0: string, arg1: string): Promise<UUID> {
        if (this.processError) {
            try {
                const result = await this.actor.createMainTopic(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMainTopic(arg0, arg1);
            return result;
        }
    }
    async createSubTopic(arg0: UUID, arg1: string, arg2: string, arg3: Difficulty, arg4: Time): Promise<UUID> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubTopic(arg0, arg1, arg2, to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubTopic(arg0, arg1, arg2, to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async deleteMainTopic(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMainTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMainTopic(arg0);
            return result;
        }
    }
    async deleteSubTopic(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubTopic(arg0);
            return result;
        }
    }
    async getAllPlannedRevisionDates(): Promise<Array<{
        plannedDates: Array<Time>;
        owner: Principal;
        difficulty: Difficulty;
        subTopicId: UUID;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlannedRevisionDates();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlannedRevisionDates();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDefaultIntervalDays(): Promise<{
        easy: Array<bigint>;
        hard: Array<bigint>;
        medium: Array<bigint>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultIntervalDays();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultIntervalDays();
            return result;
        }
    }
    async getIntervalForDifficulty(arg0: Difficulty): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIntervalForDifficulty(to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIntervalForDifficulty(to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getMainTopics(): Promise<Array<MainTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMainTopics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMainTopics();
            return result;
        }
    }
    async getPlannedRevisionDates(arg0: UUID): Promise<Array<Time> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlannedRevisionDates(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlannedRevisionDates(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevisionSchedule(): Promise<Array<RevisionSchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevisionSchedule();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevisionSchedule();
            return result;
        }
    }
    async getSubTopics(): Promise<Array<SubTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubTopics();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubTopics();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubTopicsByMainTopic(arg0: UUID): Promise<Array<SubTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubTopicsByMainTopic(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubTopicsByMainTopic(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubTopicsForDate(arg0: Time): Promise<Array<SubTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubTopicsForDate(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubTopicsForDate(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubTopicsWithStudyDates(): Promise<Array<SubTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubTopicsWithStudyDates();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubTopicsWithStudyDates();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaySubTopics(): Promise<Array<SubTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaySubTopics();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaySubTopics();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopicsWithHierarchy(): Promise<{
        subTopics: Array<SubTopic>;
        mainTopics: Array<MainTopic>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopicsWithHierarchy();
                return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopicsWithHierarchy();
            return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSettings(): Promise<{
        easyIntervals: Array<bigint>;
        mediumIntervals: Array<bigint>;
        preferredReviewDays: Array<bigint>;
        hardIntervals: Array<bigint>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markRevisionAsReviewed(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markRevisionAsReviewed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRevisionAsReviewed(arg0);
            return result;
        }
    }
    async markSubTopicCompleted(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSubTopicCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSubTopicCompleted(arg0);
            return result;
        }
    }
    async markSubTopicPending(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSubTopicPending(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSubTopicPending(arg0);
            return result;
        }
    }
    async rescheduleRevisionToNextDay(arg0: UUID): Promise<RevisionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.rescheduleRevisionToNextDay(arg0);
                return from_candid_RevisionResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rescheduleRevisionToNextDay(arg0);
            return from_candid_RevisionResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async scheduleNextReview(arg0: UUID, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleNextReview(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleNextReview(arg0, arg1);
            return result;
        }
    }
    async setUserSettings(arg0: Array<bigint>, arg1: Array<bigint>, arg2: Array<bigint>, arg3: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserSettings(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserSettings(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateIntervalIndex(arg0: UUID, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIntervalIndex(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIntervalIndex(arg0, arg1);
            return result;
        }
    }
    async updateMainTopic(arg0: UUID, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMainTopic(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMainTopic(arg0, arg1, arg2);
            return result;
        }
    }
    async updateRevisionSchedule(arg0: UUID): Promise<RevisionSchedule> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRevisionSchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRevisionSchedule(arg0);
            return result;
        }
    }
    async updateSubTopic(arg0: UUID, arg1: string, arg2: string, arg3: Difficulty, arg4: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubTopic(arg0, arg1, arg2, to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubTopic(arg0, arg1, arg2, to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
function from_candid_Difficulty_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RevisionResult_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RevisionResult): RevisionResult {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_SubTopic_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubTopic): SubTopic {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Time>]): Array<Time> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        easyIntervals: Array<bigint>;
        mediumIntervals: Array<bigint>;
        preferredReviewDays: Array<bigint>;
        hardIntervals: Array<bigint>;
    }]): {
    easyIntervals: Array<bigint>;
    mediumIntervals: Array<bigint>;
    preferredReviewDays: Array<bigint>;
    hardIntervals: Array<bigint>;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RevisionSchedule]): RevisionSchedule | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UUID;
    title: string;
    lastReviewed: [] | [_Time];
    currentIntervalIndex: bigint;
    owner: Principal;
    difficulty: _Difficulty;
    completed: boolean;
    description: string;
    creationDate: _Time;
    studyDate: _Time;
    mainTopicTitle: string;
    mainTopicId: _UUID;
}): {
    id: UUID;
    title: string;
    lastReviewed?: Time;
    currentIntervalIndex: bigint;
    owner: Principal;
    difficulty: Difficulty;
    completed: boolean;
    description: string;
    creationDate: Time;
    studyDate: Time;
    mainTopicTitle: string;
    mainTopicId: UUID;
} {
    return {
        id: value.id,
        title: value.title,
        lastReviewed: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.lastReviewed)),
        currentIntervalIndex: value.currentIntervalIndex,
        owner: value.owner,
        difficulty: from_candid_Difficulty_n7(_uploadFile, _downloadFile, value.difficulty),
        completed: value.completed,
        description: value.description,
        creationDate: value.creationDate,
        studyDate: value.studyDate,
        mainTopicTitle: value.mainTopicTitle,
        mainTopicId: value.mainTopicId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subTopics: Array<_SubTopic>;
    mainTopics: Array<_MainTopic>;
}): {
    subTopics: Array<SubTopic>;
    mainTopics: Array<MainTopic>;
} {
    return {
        subTopics: from_candid_vec_n13(_uploadFile, _downloadFile, value.subTopics),
        mainTopics: value.mainTopics
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    message: string;
    updatedSchedule: [] | [_RevisionSchedule];
    success: boolean;
}): {
    message: string;
    updatedSchedule?: RevisionSchedule;
    success: boolean;
} {
    return {
        message: value.message,
        updatedSchedule: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.updatedSchedule)),
        success: value.success
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    plannedDates: Array<_Time>;
    owner: Principal;
    difficulty: _Difficulty;
    subTopicId: _UUID;
}): {
    plannedDates: Array<Time>;
    owner: Principal;
    difficulty: Difficulty;
    subTopicId: UUID;
} {
    return {
        plannedDates: value.plannedDates,
        owner: value.owner,
        difficulty: from_candid_Difficulty_n7(_uploadFile, _downloadFile, value.difficulty),
        subTopicId: value.subTopicId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): Difficulty {
    return "easy" in value ? Difficulty.easy : "hard" in value ? Difficulty.hard : "medium" in value ? Difficulty.medium : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubTopic>): Array<SubTopic> {
    return value.map((x)=>from_candid_SubTopic_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    plannedDates: Array<_Time>;
    owner: Principal;
    difficulty: _Difficulty;
    subTopicId: _UUID;
}>): Array<{
    plannedDates: Array<Time>;
    owner: Principal;
    difficulty: Difficulty;
    subTopicId: UUID;
}> {
    return value.map((x)=>from_candid_record_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Difficulty_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == Difficulty.easy ? {
        easy: null
    } : value == Difficulty.hard ? {
        hard: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
